### ISSUE TITLE
Santa 0.9.30: santa-driver kext signature validation error

### ISSUE THREAD

**Issue by ameyah** [google/santa#364] opened 2019-05-08 16:16 UTC
I have Santa 0.9.30 on my machine. When I go to System Report > Software > Extensions (shows all the kexts on the system), `santa-driver` has signature validation error:

```
santa-driver:

  Version:	0.9.30
  Last Modified:	9/26/18, 10:17 AM
  Bundle ID:	com.google.santa-driver
  Loaded:	Yes
  Obtained from:	Unknown
  Kind:	Intel
  Architectures:	x86_64
  64-Bit (Intel):	Yes
  Location:	/Library/Extensions/santa-driver.kext
  Kext Version:	0.9.30
  Load Address:	18446743521900100000
  Loadable:	No
  Signature Validation Errors:	Kext signature validation error code -67023
  Dependencies:	Satisfied
  Signed by:	Unknown
```

Can you reproduce the same on your end?

When I use `santactl fileinfo` on the same kext, it does show up the signing certificate.

**Comment by russellhancox** [comment] 2019-05-08 16:41
Yes, there was an issue with the 0.9.30 release where the `Contents/_CodeSignature` directory had 0640 permission, which prevents non-root processes from verifying the signature. You can verify this yourself:

```
» codesign --strict -vv /Library/Extensions/santa-driver.kext
/Library/Extensions/santa-driver.kext: invalid resource directory (directory or signature have been modified)
» sudo codesign --strict -vv /Library/Extensions/santa-driver.kext
/Library/Extensions/santa-driver.kext: valid on disk
/Library/Extensions/santa-driver.kext: satisfies its Designated Requirement
```

We fixed this in the 0.9.31 release, among other things.

Dupe of #325

**Closed by russellhancox** 2019-05-08 16:41 UTC
Labels: duplicate
