### ISSUE TITLE
Santa doesn't block scripts

### ISSUE THREAD

**Issue by sailingobviously** [google/santa#1117] opened 2023-06-29 09:10 UTC
Santa [doesn't](https://github.com/google/santa/issues/348) stop scripts from running, Windows XP's [Software Restriction Policy](https://www.oreilly.com/library/view/microsoft-windows-internals/0735619174/ch08s09.html) can do this.

.pkg files are [executed](https://www.praetorian.com/blog/bypassing-google-santa-application-whitelisting-on-macos-part-1/
) [without](https://www.praetorian.com/blog/bypassing-google-santa-application-whitelisting-on-macos-part-2/) hindrance.

> Scripts: Santa is currently written to ignore any execution that isn't a binary. This is because after weighing the administration cost vs the benefit, we found it wasn't worthwhile. Additionally, a number of applications make use of temporary generated scripts, which we can't possibly allowlist and not doing so would cause problems. We're happy to revisit this (or at least make it an option) if it would be useful to others.

This would solve our malware problems, does Google use Santa to mitigate malware?

**Comment by russellhancox** [comment] 2023-06-29 14:18
This is a documented limitation and the reasoning is explained. We are actively exploring ways to do achieve this that are both performant and do not become an administrative headache. 

Closing as dupe of #348.

**Closed by russellhancox** 2023-06-29 14:18 UTC

**Comment by sailingobviously** [comment] 2023-06-30 02:46
> We are actively exploring ways 

Closing this as not planned seems orthogonal to actively working on it

**Comment by russellhancox** [comment] 2023-06-30 02:47
"Closing as dupe of https://github.com/google/santa/issues/348."
