### ISSUE TITLE
Incorrect event decision code being synced to server (ALLOW_UNKNOWN instead of ALLOW_TEAMID)

### ISSUE THREAD

**Issue by p-harrison** [google/santa#1136] opened 2023-07-27 18:23 UTC
My understanding is that a machine in Monitor mode that allows a binary to run where there is no rule match would report ALLOW_UNKNOWN as the decision, whereas if there is a rule match it would report perhaps ALLOW_BINARY or ALLOW_TEAMID?

Looking through the events synced to my server from machines configured with EnableAllEventUpload=true for the last couple of weeks, there are no ALLOW_TEAMID or ALLOW_SIGNINGID decisions, even though I have some of both types of rules defined and they correctly permit a binary to run on a machine in lockdown.  There are a small number of ALLOW_BINARY and ALLOW_CERTIFICATE while all the rest are ALLOW_UNKNOWN.

For example here is a fileinfo output from a machine in lockdown -
```
santactl fileinfo "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Renderer).app"

Path                   : /Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Renderer).app/Contents/MacOS/Microsoft Teams Helper (Renderer)
SHA-256                : 37a29529c7231e442a909851c6b7cbb9b4446e7bc3c7aad393c99905e2c1ff3d
SHA-1                  : 80afb32a1d781235a2804e3c7945c1f205b8e734
Bundle Name            : Microsoft Teams Helper (Renderer)
Bundle Version         : 617554
Bundle Version Str     : 1.00.617554
Team ID                : UBF8T346G9
Signing ID             : com.microsoft.teams.helper
Type                   : Executable (arm64, x86_64)
Code-signed            : Yes
Rule                   : Allowed (TeamID)
```

Here is what was sent to the sync server for the same binary being executed on a different machine in monitor mode with the same ruleset applied -
```
{
                "signing_id": "UBF8T346G9:com.microsoft.teams.helper",
                "ppid": 62973,
                "file_bundle_version_string": "1.00.617554",
                "signing_chain": [
                    {
                        "cn": "Developer ID Application: Microsoft Corporation (UBF8T346G9)",
                        "valid_until": 1801519935,
                        "org": "Microsoft Corporation",
                        "valid_from": 1682631978,
                        "ou": "UBF8T346G9",
                        "sha256": "ae48e0bf4bbb344d43696f4fba9fc64da7a2ad91d528dc47979f6e7ebdf51ae8"
                    },
                    {
                        "cn": "Developer ID Certification Authority",
                        "valid_until": 1801519935,
                        "org": "Apple Inc.",
                        "valid_from": 1328134335,
                        "ou": "Apple Certification Authority",
                        "sha256": "7afc9d01a62f03a2de9637936d4afe68090d2de18d03f29c88cfb0b1ba63587f"
                    },
                    {
                        "cn": "Apple Root CA",
                        "valid_until": 2054670036,
                        "org": "Apple Inc.",
                        "valid_from": 1146001236,
                        "ou": "Apple Certification Authority",
                        "sha256": "b0b1730ecbc7ff4505142c49f1295e6eda6bcaed7e2c68c5be91b5a11001f024"
                    }
                ],
                "file_bundle_path": "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Renderer).app",
                "file_name": "Microsoft Teams Helper (Renderer)",
                "file_bundle_version": "617554",
                "parent_name": "Teams",
                "quarantine_timestamp": 0,
                "file_bundle_name": "Microsoft Teams Helper (Renderer)",
                "executing_user": "********",
                "current_sessions": [
                    "******@console"
                ],
                "file_bundle_id": "com.microsoft.teams.helper",
                "file_path": "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Renderer).app/Contents/MacOS",
                "file_sha256": "37a29529c7231e442a909851c6b7cbb9b4446e7bc3c7aad393c99905e2c1ff3d",
                "decision": "ALLOW_UNKNOWN",
                "pid": 46071,
                "execution_time": 1690454845.0466108,
                "logged_in_users": [
                    "**********"
                ],
                "team_id": "UBF8T346G9"
            }
```

**Comment by pmarkowsky** [comment] 2023-07-29 01:57
Was able to reproduce this behavior with moroz tonight. Will start digging in on Monday.

**Comment by pmarkowsky** [comment] 2023-07-29 02:37
Found a bug in my setup. Rebuilt a debug build from current main 39ee9e7d

Now I can't seem to reproduce when the sync service sends `enable_all_event_upload`. I'm correctly seeing `ALLOW_TEAMID`.

```json
{
		"signing_id": "6JSW4SJWN9:md.obsidian",
		"ppid": 71434,
		"file_bundle_version_string": "1.3.5",
		"signing_chain": [{
			"cn": "Developer ID Application: Dynalist Inc. (6JSW4SJWN9)",
			"valid_until": 1777314401,
			"org": "Dynalist Inc.",
			"valid_from": 1619461602,
			"ou": "6JSW4SJWN9",
			"sha256": "dd6612df0cc1858a5a41a145b5daff747e1cf133a905102a1d2f1218d9d067e7"
		}, {
			"cn": "Developer ID Certification Authority",
			"valid_until": 1801519935,
			"org": "Apple Inc.",
			"valid_from": 1328134335,
			"ou": "Apple Certification Authority",
			"sha256": "7afc9d01a62f03a2de9637936d4afe68090d2de18d03f29c88cfb0b1ba63587f"
		}, {
			"cn": "Apple Root CA",
			"valid_until": 2054670036,
			"org": "Apple Inc.",
			"valid_from": 1146001236,
			"ou": "Apple Certification Authority",
			"sha256": "b0b1730ecbc7ff4505142c49f1295e6eda6bcaed7e2c68c5be91b5a11001f024"
		}],
		"file_bundle_path": "\/Applications\/Obsidian.app",
		"file_name": "Obsidian",
		"file_bundle_version": "0.14.8",
		"parent_name": "zsh",
		"quarantine_timestamp": 0,
		"file_bundle_name": "Obsidian",
		"executing_user": "*******",
		"current_sessions": ["********" ],
		"file_bundle_id": "md.obsidian",
		"file_path": "\/Applications\/Obsidian.app\/Contents\/MacOS",
		"file_sha256": "f19ec12f530a377755bace8659579f513f30603f91e64da1f08147373512099d",
		"decision": "ALLOW_TEAMID", 
		"pid": 79420,
		"execution_time": 1690597242.4550261,
		"logged_in_users": ["*******"],
		"team_id": "6JSW4SJWN9"
	}
```

@p-harrison are the hosts you're seeing this behavior in Monitor or Lockdown mode? Also what rules and versions of Santa are you seeing the behavior with?

**Comment by p-harrison** [comment] 2023-07-29 05:48
The machines I’m seeing it with are in Monitor mode. However I only have enable_all_event_upload enabled on my Monitor mode machines, so I couldn’t say if it is also happening with Lockdown machines. I could test over the weekend though.

Santa version is 2023.6.546101548.

**Comment by p-harrison** [comment] 2023-08-04 11:33
@pmarkowsky while troubleshooting #1137, I added `enable_all_event_upload:true` to the PreFlight response of all our machines (whereas I had been setting this via Managed Preferences previously).  At the next sync cycle, machines in Lockdown started sending ALLOW_ events (solving #1137) but strangely machines in Monitor mode started sending correct decisions (ALLOW_TEAMID rather than ALLOW_UNKNOWN) in their Event Upload stage.

So my problem has gone away which is great!  If there's any more information I can provide to help chase down this bug by all means shout.

**Comment by pmarkowsky** [comment] 2023-08-04 18:03
>[S]trangely machines in Monitor mode started sending correct decisions (ALLOW_TEAMID rather than ALLOW_UNKNOWN) in their Event Upload stage.

That seems odd. After fixing an issue with my moroz setup I've been unable to reproduce the behavior.  Looking at our test coverage I'm confident that Santa should be doing the right thing, so I'm going to close this issue.  That said you can get odd results if things change from the sync service.  #1142 should make this behavior more stable. 

If it comes back please feel free to reopen this issue and thanks for the solid bug reports.

**Closed by pmarkowsky** 2023-08-04 18:03 UTC
Labels: bug
