### ISSUE TITLE
SantaGUI headline not centered and ugly

### ISSUE THREAD

**Issue by tburgin** [google/santa#159] opened 2017-04-04 19:42 UTC
Looks like this takes place with the commit a2a660d483d5bcd27c3c5ee9e581657af60f9400. Dropping this commit fixes the issue.
Something doesn't like the use of modules I guess.

Eww.
<img width="532" alt="screen shot 2017-04-04 at 3 39 08 pm" src="https://cloud.githubusercontent.com/assets/2117646/24675384/f0f20eba-194c-11e7-8606-d72d0808937a.png">

When clicking on the text it turns black?
<img width="532" alt="screen shot 2017-04-04 at 3 39 03 pm" src="https://cloud.githubusercontent.com/assets/2117646/24675385/f125d3bc-194c-11e7-9cd0-ef438708f1f6.png">

**Comment by tburgin** [comment] 2017-04-04 20:00
Re-adding a pch for just SantaGUI fixes the issue 😕

**Comment by russellhancox** [comment] 2017-04-04 20:25
This is caused by [this ifdef](https://github.com/google/santa/blob/master/Source/common/SNTBlockMessage.m#L54), which exists because NSAttributedString's `initWithHTML:documentAttributes` method is defined in an AppKit extension (NSAttributedStringUIFoundationAdditions in UIFoundation.framework) and SNTBlockMessage is _common_ code - the ifdef worked because of the way PCH's worked vs modules.

I'm sure there's an easy way we can check that AppKit is available that still works for modules.

**Comment by russellhancox** [comment] 2017-04-04 21:09
Fixed with #161

**Closed by russellhancox** 2017-04-04 21:09 UTC
Labels: bug
