### ISSUE TITLE
deadline exceeded in monitor mode still ends up denying execution

### ISSUE THREAD

**Issue by jessepeterson** [google/santa#1283] opened 2024-02-07 21:18 UTC
When deadlines are exceeded here:

https://github.com/google/santa/blob/e8db89c57c41dde73fa447bca206faf9075eb484/Source/santad/EventProviders/SNTEndpointSecurityClient.mm#L296-L299

The process is still denied execution even if Santa is in monitor mode.

Also: these denials are not logged in the normal ALLOW/DENY logging (that end up in `/var/db/santa/santa.log*` files.

**Comment by russellhancox** [comment] 2024-02-07 21:21
> The process is still denied execution even if Santa is in monitor mode.

That's correct and working as intended. Monitor mode is intended to allow through things that we didn't have explicit rules for but it still applies block rules and we don't want to allow working around those rules by making everything slow enough that we can't finish processing in time.

> Also: these denials are not logged in the normal ALLOW/DENY logging (that end up in /var/db/santa/santa.log* files.

That's working as _designed_ but should be fixed. Before ULS the two kinds of logs ended up in the same file so it was still together. Now that these log lines end up in the system log it's not the right solution.

**Comment by mlw** [comment] 2024-02-07 21:24
> The process is still denied execution even if Santa is in monitor mode.

One thing we might want to consider is whether or not `FailClosed` config option should apply

**Comment by russellhancox** [comment] 2024-02-07 21:51
> Also: these denials are not logged in the normal ALLOW/DENY logging (that end up in /var/db/santa/santa.log* files.

I want to make sure we're clear about this: the normal ALLOW/DENY logging **is** happening but we're logging the decision Santa came to about the file but what we're logging is incorrect because prior to us responding that the exec should be allowed we've already denied exec because we'd have gone over deadline while processing. This is arguably worse.

**Closed** 2024-02-08 20:12 UTC
Labels: bug
