### ISSUE TITLE
On macOS sierra, there's no /var/log/santa.log file.

### ISSUE THREAD

**Issue by stanfordzhang** [google/santa#109] opened 2016-10-10 10:00 UTC
I tried many times. 
Maybe because of _Unified Logging_. (https://developer.apple.com/library/content/releasenotes/MacOSX/WhatsNewInOSX/Articles/OSXv10.html)

or I need to turn on some nvram args?

Expecting new update!

**Comment by arubdesu** [comment] 2016-10-10 13:33
There have been no compatibility issues with Sierra and the current asl.conf method of logging. Unified logging, while shipped as a replacement for all API's, only means that `asl` is deprecated. Please describe the steps you performed and are not seeing those log files created.

**Comment by russellhancox** [comment] 2016-10-10 16:38
This is due to building with the 10.12 SDK, building with the 10.11 SDK from Xcode 7.3.1 seems to work fine.

**Comment by russellhancox** [comment] 2016-10-10 16:38
Marking as dupe of #110

**Closed by russellhancox** 2016-10-10 16:38 UTC
Labels: duplicate

**Comment by stanfordzhang** [comment] 2016-10-11 03:22
@russellhancox Yes, it works fine on 10.11. Thank you! However, do you know why the logging configuration does not work when running on 10.12? And would you rewrite SNTLogging with unified logging on 10.12? They are so different.

**Comment by stanfordzhang** [comment] 2016-10-11 03:24
@arubdesu I got the answer from russell hancox. Thank you.

**Comment by russellhancox** [comment] 2016-10-11 15:43
> However, do you know why the logging configuration does not work when running on 10.12?

It only doesn't work if Santa is built with the 10.12 SDK. If you use the released Santa 0.9.13 (which was built with the 10.11 SDK) on 10.12, the existing configuration works fine (or at least, it has in my testing on several machines).

> And would you rewrite SNTLogging with unified logging on 10.12?

No, as we support 10.9+ adding support for unified logging would mean doing runtime checks for the OS version and switching log functions accordingly. Given that Apple says the existing `asl_*` functions should continue to work by re-directing to unified logging, there's not a good reason to switch.

**Comment by stanfordzhang** [comment] 2016-10-13 07:36
@russellhancox Thanks!
