### ISSUE TITLE
Transitive rules with Xcode

### ISSUE THREAD

**Issue by leohidalgo** [google/santa#456] opened 2020-03-27 03:45 UTC
Hi, I'm having trouble with transitive rules again, everything was working ok until the last Catalina update, 10.15.4.

The problem:
- I added compilation rules for codesign and ld, these work the first time I compile with Xcode.
- I remove DerivedData and compile again and Santa tells me that the execution has been blocked.
- I add the same compilation rules again and Santa lets me run

With each iteration the number of `binary rules` increases.

`santactl status`

```BASH
>>> Daemon Info
  Driver Connected          | Yes
  Mode                      | Lockdown
  File Logging              | Yes
  Watchdog CPU Events       | 6  (Peak: 47.38%)
  Watchdog RAM Events       | 0  (Peak: 65.54MB)
>>> Database Info
  Binary Rules              | 102
  Certificate Rules         | 42
  Compiler Rules            | 2
  Transitive Rules          | 73
```

`santactl version`

```
santa-driver    | un-needed (SystemExtension being used)
santad          | 1.12
santactl        | 1.12
SantaGUI        | 1.12
```

Issue related: #407 

**Update:** With `0.9.33` version everything work ok, any idea what might be happening with latest version?

**Comment by russellhancox** [comment] 2020-04-06 16:26
Sorry for the delayed response, I've been trying to reproduce this with no luck.

Do you see log lines matching `action=WRITE` for the binary that's being executed? 

It's odd that you're seeing the number of binary rules go up; the rules made in transitive mode should show up as transitive rules not binary rules.

**Comment by leohidalgo** [comment] 2020-04-19 04:51
> Do you see log lines matching `action=WRITE` for the binary that's being executed?
No, only I see WRITE when I add a ruler again, but all I have to do is remove DerivedData and it blocks me again.

Now I try with Santa 1.13, I format my MacBook and I problem is the same.

Log:
`$ cat santa.log | grep Demo.app/Demo`

https://pastebin.com/4njEAx7u

**Comment by leohidalgo** [comment] 2020-04-19 17:46
> Version 1.12 should log an info message when it creates transitive rules. Is anything being logged?
> 
> Something like this will show you logs for the last hour:
> 
> ```
> log show --info --predicate 'message CONTAINS[c] "santa"' --last 1h
> ```

Log when it fails
https://pastebin.com/YRkBP9bF

Log when it success
https://pastebin.com/TeAy2xqw

**Comment by pmarkowsky** [comment] 2023-04-21 16:10
Closing as the issue is 3 years old. 

This seems very similar to the transitive allow listing discussion in #561.

**Closed by pmarkowsky** 2023-04-21 16:10 UTC
