### ISSUE TITLE
Compiler Rule for Golang Not Working

### ISSUE THREAD

**Issue by eopeter** [google/santa#1061] opened 2023-03-28 02:32 UTC
I have Santa in Lockdown mode; I am able to build binaries written in golang but when I attempt to run using `go run .`, it gets blocked pointing to the build output as shown. I have 2 compiler rules but no transitive rules. I added the compiler rule by adding a binary rule for the `go` binary with the `ALLOWLIST_COMPILER` policy but does not work. Why are there no transitive rules? I didn't think I need to create those and assumed they were added automatically.

```bash
$ go run .
signal: killed

Santa

This application has been blocked.

Path:       /private/var/folders/9_/5335k32d7391gkc9jx2jhyhm001slv/T/go-build3160128926/b001/exe/output
Identifier: 7cf585e83a88a7a5215d38fdb27319e8acdad2e943ce6265e350cd1693ad71d6
Parent:     go (66020)
```

### santactl status
```
>>> Daemon Info
  Mode                      | Lockdown
  Log Type                  | file
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 3  (Peak: 34.87%)
  Watchdog RAM Events       | 0  (Peak: 80.61MB)
>>> Cache Info
  Root cache count          | 313
  Non-root cache count      | 4
>>> Database Info
  Binary Rules              | 94
  Certificate Rules         | 4
  TeamID Rules              | 54
  Compiler Rules            | 2
  Transitive Rules          | 0
  Events Pending Upload     | 19
>>> Watch Items
  Enabled                   | No
>>> Sync Info
  Sync Server               | http://localhost/v1/santa/
  Clean Sync Required       | No
  Last Successful Full Sync | 2023/03/27 14:14:53 -0400
  Last Successful Rule Sync | 2023/03/27 14:14:53 -0400
  Push Notifications        | Disconnected
  Bundle Scanning           | Yes
  Transitive Rules          | Yes
>>> Metrics Info
  Metrics Server            | http://localhost/santa/metrics/
  Export Interval (seconds) | 30
```

**Comment by eopeter** [comment] 2023-03-29 10:51
This seems to be related to #561. So I have added a AllowRegexPath to `^\/private\/var\/folders\/.*go\-build.*\/.*\/exe\/.*$`

**Comment by pmarkowsky** [comment] 2023-04-01 19:03
The issue here is that the go toolchain opens the files for write and then mmaps the file descriptor writeable to avoid doing a lot of write system calls. When tools do this Apple's Endpoint Security Framework reports the file isn't modified for close events which is what Santa uses to the track newly created files and given them new allow rules.

So this is effectively a duplicate of #561. 

I'm going to close this so that we keep the main discussion in #561.

**Closed by pmarkowsky** 2023-04-01 19:03 UTC

**Comment by eopeter** [comment] 2023-04-01 19:13
Sounds good. Thank you!!
