### ISSUE TITLE
File based certificates

### ISSUE THREAD

**Issue by dsklopp** [google/santa#610] opened 2021-09-23 15:01 UTC
Hello,

I am experimenting with using file based certificates for Santa authentication.  From looking through the documentation it appears all that is necessary is the setting of three options: ClientAuthCertificateFile, ClientAuthCertificateCN to the CN of the file and ClientAuthCertificatePassword.  We already have a functioning solution using certs in the system keychain, and we are using the same certificate in the system keychain as we are on disk.

However, when using file based certs I get one of two errors.  Is this expected behavior or is there a missing configuration?

First one without a password and ClientAuthCertificatePassword set to empty string (and cert bundle created with empty string).

`
Preflight starting
Performing request, attempt 1
Server Trust: /O=REDACTED/OU=(null)/CN=REDACTED/SHA-1=REDACTED
Client Trust: Couldn't load client certificate /Users/dsklopp/testcerts/machine_cert.p12: -25264
Server asked for client authentication but no usable client certificate found.
Failed to decode JSON response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Failed to decode JSON response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Rule download failed, aborting run

`

When set with a password to 'asdf' on both the bundle and the ClientAuthCertificatePassword option

`
Preflight starting
Performing request, attempt 1
Server Trust: /O=REDACTED/OU=(null)/CN=REDACTED/SHA-1=REDACTED
Server asked for client authentication but no usable client certificate found.
Failed to decode JSON response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Failed to decode JSON response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Rule download failed, aborting run

`

**Comment by russellhancox** [comment] 2021-09-23 15:31
OK, firstly, you don't need to set `ClientAuthCertificateCN` when using a file, that key is used to find a certificate that is already in the System keychain. For file-based certs you need to set `ClientAuthCertificateFile` and `ClientAuthCertificatePassword`.

Your first set of output shows that Santa did try to import the file and returned status `-25264` which corresponds to [errSecPkcs12VerifyFailure](https://osstatus.com/search/results?platform=all&framework=Security&search=-25264), which is happening because the Security framework refuses to import a PKCS#12 without a password.

Your second set of output shows it still failing despite having a password set but this time there isn't a useful explanation as to why. Based on the output I would guess that the PKCS#12 is importing successfully but the certificate that was imported is not considered valid for the server you're connecting to, likely because the issuer doesn't match one that the server says it will accept.

+ Is the certificate in that last output issued by the CN registered with the HTTPS server? 
+ If you run `sudo santactl sync --debug`, does this provide more useful output?
+ If all else fails you can `sudo CFNETWORK_DIAGNOSTICS=1 santactl sync` and then immediately after run `sudo log show --process santactl --last 2m` to get _very_ detailed logs about what happened. Somewhere in this output will be a line like `Connection 1: issuing challenge for client certificates` which lists how many DNs are accepted and following this will be lots of lines from the Security framework indicating the progress it's making evaluating available certificates. This should give some indication as to where the problem is.

**Comment by dsklopp** [comment] 2021-09-23 16:56
--debug doesn't offer anymore information.

It is registered.

I'm parsing the output from CFNETWORK_DIAGNOSTICS=1 now, it is rather verbose.

**Comment by pmarkowsky** [comment] 2022-07-28 16:07
Marking this as closed, since there's been no update in 10 months. If this is still an issue please update and reopen.

**Closed by pmarkowsky** 2022-07-28 16:07 UTC
Labels: question
